version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies
      - gcloud:
          name: Setup GCloud SDK
          command: curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-291.0.0-linux-x86_64.tar.gz | tar xvz - -C ~/.gradle
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: app/reports
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: feature/users/build/reports
          destination: feature/users/reports
      - store_artifacts:
          path: feature/push/build/reports
          destination: feature/push/reports
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: feature/users/build/test-results
      - store_test_results:
          path: feature/push/build/test-results


