version: 2.4.4
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android-api/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android-api/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check --stacktrace --max-workers=2 --no-daemon
      - run:
          name: Run Tests Firebase
          command: ./gradlew runInstrumentedTestsOnFirebase --stacktrace --no-daemon
  moduleStatisticsReport:
    environment:
      JVM_OPTS: -Xmx4096m
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Execute Data Processing
          command: ./gradlew reportModuleStatistics --max-workers=2 --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  check:
    jobs:
      - build
  statisticsReport:
    triggers:
      - schedule:
          cron: "0 8 * * *" # Every Day at 8:00 UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - moduleStatisticsReport

