version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "client/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "client/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-android/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: client/build/reports
          destination: client/reports
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: client-data/build/reports
          destination: client-data/reports
      - store_test_results:
          path: client/build/test-results
      - store_test_results:
          path: client-data/build/test-results
      - store_test_results:
          path: core/build/test-results

