name: Build
on: [push]
env:
  GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
jobs:
  build-check-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: build-${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Get Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies --stacktrace
      - name: Run Tests
        run: ./gradlew check --stacktrace
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: build-${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Get Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies --stacktrace
      - name: Build Release Bundle - .aab
        env:
          CLIENT_GITHUB_KEY_PASS: ${{ secrets.CLIENT_GITHUB_KEY_PASS }}
          CLIENT_GITHUB_STORE_PASS: ${{ secrets.CLIENT_GITHUB_STORE_PASS }}
        run: ./gradlew bundleRelease --stacktrace
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: build-${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Get Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies --stacktrace
      - name: Run Tests Firebase
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
          FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
        run: ./gradlew runInstrumentedTestsOnFirebase --stacktrace
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: lint--${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Lint
        run: echo $JAVA_HOME_17_X64
