name: Trigger Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Comment'
        required: false
        default: 'Next release'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release and Bump version
        env:
          GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}
          TOKEN_GITHUB_API: ${{ secrets.CI_GITHUB_TOKEN }}
        run: ./gradlew createNewReleaseAndBumpVersion  --stacktrace
