name: Daily Reporting
on:
  schedule:
    - cron: "0 8 * * *" # Every Day at 8:00 UTC
env:
  GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
jobs:
  moduleStatisticsReport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run Module Statistics Report
        run: ./gradlew reportModuleStatistics --stacktrace --no-configure-on-demand
  lintReport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run Lint Report
        run: ./gradlew lintStatisticsReport --stacktrace
  app-size:
    name: Report Release App Size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Analyze by Ruler and Report
        env:
          CLIENT_GITHUB_KEY_PASS: ${{ secrets.CLIENT_GITHUB_KEY_PASS }}
          CLIENT_GITHUB_STORE_PASS: ${{ secrets.CLIENT_GITHUB_STORE_PASS }}
        run: ./gradlew -s reportAppSize
      - name: Upload Ruler reports
        uses: actions/upload-artifact@v4
        with:
          name: ruler-reports
          path: app/build/reports/ruler/release
