name: Daily Reporting
on:
  schedule:
    - cron: "0 8 * * *" # Every Day at 8:00 UTC
env:
  GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}
jobs:
  moduleStatisticsReport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Module Statistics Report
        run: ./gradlew reportModuleStatistics --stacktrace --no-configure-on-demand
  lintReport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Lint Report
        run: ./gradlew lintStatisticsReport --stacktrace
